worlds:
  world:
    punishThreshold: 800
    chunkGenDistance: 32
    coolingRate: 16
    coolingSpeedup: 1.25
    viewDistanceValues:
      - 8
      - 6
      - 4
    viewDistanceThresholds:
      - 1.0
      - 2.0
      - 4.0
    elytraDamage: true
    elytraDamageMultiplier: 3.0
    elytraVanish: true
    elytraVanishMultiplier: 60